# -*- coding: utf-8 -*-
"""
/***************************************************************************
 line_create
                                 A QGIS plugin
 line_create
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-06
        copyright            : (C) 2020 by arpit
        email                : arpitvk99@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load line_create class from file line_create.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .line_create import line_create
    return line_create(iface)
